# Generated by Django 3.2.12 on 2023-02-28 21:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='Полное имя')),
                ('chat_id', models.PositiveBigIntegerField(verbose_name='ID чата в ТГ')),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Администраторы',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveBigIntegerField(verbose_name='ID чата в ТГ')),
                ('requests_left', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во оставшихся запросов')),
                ('end', models.DateField(blank=True, default=datetime.datetime(2023, 4, 1, 0, 39, 26, 614495), null=True, verbose_name='Дата конца тарифа')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.PositiveBigIntegerField(verbose_name='ID чата в ТГ')),
            ],
            options={
                'verbose_name': 'Подрядчик',
                'verbose_name_plural': 'Подрядчики',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('stripe_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='ID в Stripe')),
                ('description', models.TextField(verbose_name='Описание')),
                ('request_quantity', models.PositiveSmallIntegerField(verbose_name='Количество заявок')),
                ('price', models.PositiveBigIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('dialogue', models.TextField(blank=True, verbose_name='Переписка')),
                ('files', models.JSONField(default=list, verbose_name='Файлы')),
                ('published', models.DateTimeField(default=datetime.datetime(2023, 3, 1, 0, 39, 26, 614494), verbose_name='Опубликован')),
                ('put_into_action', models.DateTimeField(blank=True, null=True, verbose_name='Взят в работу')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client', verbose_name='Клиент')),
                ('freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.freelancer', verbose_name='Подрядчик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tariff', verbose_name='Тариф'),
        ),
    ]
