# Generated by Django 3.2.12 on 2023-02-28 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='stripe_id',
        ),
        migrations.AlterField(
            model_name='client',
            name='end',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 1, 1, 9, 13, 389580), null=True, verbose_name='Дата конца тарифа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 1, 1, 9, 13, 389579), verbose_name='Опубликован'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
