# Generated by Django 3.2.12 on 2023-02-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0015_alter_client_end_alter_order_published'),
        ('telegram_bot', '0015_auto_20230223_1213'),
    ]

    operations = [
    ]
