# Generated by Django 3.2.12 on 2023-02-23 11:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0016_merge_20230223_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='end',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 23, 14, 23, 34, 582201), null=True, verbose_name='Дата конца тарифа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 14, 23, 34, 582200), verbose_name='Опубликован'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Файл к заказу',
                'verbose_name_plural': 'Файлы к заказку',
            },
        ),
    ]
